version: '3.8'

services:
  # Database services
  mongo:
    image: mongo:5.0
    container_name: adpilot_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: adpilot
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6-alpine
    container_name: adpilot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Core services
  orchestrator:
    build: 
      context: ./orchestrator
      dockerfile: Dockerfile
    container_name: adpilot_orchestrator
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/adpilot
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  test-engine:
    build:
      context: ./services/test-engine
      dockerfile: Dockerfile
    container_name: adpilot_test_engine
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/adpilot
    depends_on:
      - mongo
      - orchestrator

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: adpilot_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:4000/api
    depends_on:
      - orchestrator

volumes:
  mongo_data:
  redis_data: 